### ISSUE TITLE
pyserial import error

### ISSUE THREAD

**Issue by foong** [pushbuttons/C4D-to-Arduino#1]
hey there, 
Was getting the error that C4d cant find module named "serial""
Wanted to make sure i was placing it in the right directory.
Do you mind shining some light on the issue?

Mac version :10.11.6 el capitan
C4d version :R17
Pyserial version : 3.2.1 

Please and Thank you!

**Comment by pushbuttons** [comment]
Hi foong, C4D has it's own Python environment you can either add PySerial there, or point to another python environment.
1. To add PySerial to the C4D environment, open your C4D preferences window (cmd+ e mac or ctl + e windows), hit the 'open preferences folder' icon and navigate to /library/python/packages/ and add the PySerial directory.
2. Another option is to point to your standard/dev environment and import PySerial from there. Using your standard (non C4D environment) import the module, and print it back to the console which returns a message similar to "<module 'x' from '/usr/local/.../python2.7/site-packages/x.pyc'>. Back inside C4D you can append the path before importing your module. i.e.
import c4d, sys
sys.path.append("/usr/local/.../python2.7/site-packages")
import x

I'll add this to the README.md
